from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import DateTime, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class WorkflowModel(Base):
    """
    Persisted record for a travel planning workflow.

    Columns
    -------
    workflow_id     UUID4 string — primary key, generated by PlannerService
    user_id         Optional authenticated user identifier
    query           Raw user travel query
    status          Lifecycle state: pending | running | completed | failed
    estimated_steps Newline-separated list of planning step names
    completed_steps Newline-separated list of steps the agent has finished
    final_plan      Full Markdown travel plan produced by the LangGraph agent
    error_message   Human-readable failure reason (null on success)
    created_at      UTC timestamp set on INSERT
    updated_at      UTC timestamp updated on every UPDATE
    """

    __tablename__ = "workflows"

    workflow_id: Mapped[str] = mapped_column(String(36), primary_key=True)
    user_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending", index=True)

    # Step tracking — stored as newline-joined strings for portability
    estimated_steps: Mapped[str] = mapped_column(Text, nullable=False, default="")
    completed_steps: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Agent output
    final_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Timestamps — server_default uses DB-side NOW() for reliability
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def encode_steps(steps: list[str]) -> str:
        return "\n".join(steps)

    @staticmethod
    def decode_steps(raw: str) -> list[str]:
        return [s for s in raw.split("\n") if s.strip()]

    def __repr__(self) -> str:
        return f"<WorkflowModel id={self.workflow_id!r} status={self.status!r}>"
