"""
app/main.py
-----------
FastAPI application entrypoint.

Responsibilities:
- Construct the FastAPI app with metadata
- Register global exception handlers
- Mount the API router
- Log startup / shutdown lifecycle events
"""

from __future__ import annotations

import logging

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.api.router import router
from app.core import (
    AgenticBaseError,
    NotFoundError,
    ValidationError,
    WorkflowError,
    get_logger,
    settings,
)

logger = get_logger(__name__)


# ── Application factory ───────────────────────────────────────────────────────

def create_app() -> FastAPI:
    """
    Build and configure the FastAPI application.
    Separating construction into a factory makes the app easier to test.
    """
    app = FastAPI(
        title=settings.APP_NAME,
        version=settings.APP_VERSION,
        description=(
            "**Agentic Travel AI** — an AI-powered travel planning backend.\n\n"
            "Submit a natural-language travel request and receive a structured, "
            "day-by-day itinerary generated by an autonomous planning agent."
        ),
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
        debug=settings.DEBUG,
    )

    # ── CORS ──────────────────────────────────────────────────────────────────
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.ALLOWED_ORIGINS,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ── Global exception handlers ─────────────────────────────────────────────
    _register_exception_handlers(app)

    # ── Routers ───────────────────────────────────────────────────────────────
    app.include_router(router, prefix="/api")

    # ── Lifecycle ─────────────────────────────────────────────────────────────
    @app.on_event("startup")
    async def on_startup() -> None:
        logger.info(
            "🚀 %s v%s starting up [env=%s, log_level=%s]",
            settings.APP_NAME,
            settings.APP_VERSION,
            settings.APP_ENV,
            settings.LOG_LEVEL,
        )

    @app.on_event("shutdown")
    async def on_shutdown() -> None:
        logger.info("🛑 %s shutting down.", settings.APP_NAME)

    return app


# ── Exception handler registration ───────────────────────────────────────────

def _register_exception_handlers(app: FastAPI) -> None:
    """
    Map custom domain exceptions to structured JSON error responses.

    All handlers follow the same envelope:
        {
            "error_code": "NOT_FOUND",
            "message": "Workflow 'abc' not found.",
            "details": { ... }   # optional
        }
    """

    @app.exception_handler(AgenticBaseError)
    async def agentic_base_error_handler(
        request: Request, exc: AgenticBaseError
    ) -> JSONResponse:
        logger.warning(
            "Domain error [%s]: %s",
            exc.error_code,
            exc.message,
            extra={"path": request.url.path, "details": exc.details},
        )
        return JSONResponse(
            status_code=exc.status_code,
            content=exc.to_dict(),
        )

    @app.exception_handler(ValidationError)
    async def validation_error_handler(
        request: Request, exc: ValidationError
    ) -> JSONResponse:
        logger.warning(
            "Validation error: %s", exc.message,
            extra={"path": request.url.path, "details": exc.details},
        )
        return JSONResponse(
            status_code=exc.status_code,
            content=exc.to_dict(),
        )

    @app.exception_handler(NotFoundError)
    async def not_found_error_handler(
        request: Request, exc: NotFoundError
    ) -> JSONResponse:
        logger.info(
            "Not found: %s", exc.message,
            extra={"path": request.url.path, "details": exc.details},
        )
        return JSONResponse(
            status_code=exc.status_code,
            content=exc.to_dict(),
        )

    @app.exception_handler(WorkflowError)
    async def workflow_error_handler(
        request: Request, exc: WorkflowError
    ) -> JSONResponse:
        logger.error(
            "Workflow error: %s", exc.message,
            extra={"path": request.url.path, "details": exc.details},
        )
        return JSONResponse(
            status_code=exc.status_code,
            content=exc.to_dict(),
        )

    @app.exception_handler(Exception)
    async def unhandled_exception_handler(
        request: Request, exc: Exception
    ) -> JSONResponse:
        logger.exception(
            "Unhandled exception on %s: %s", request.url.path, exc
        )
        return JSONResponse(
            status_code=500,
            content={
                "error_code": "INTERNAL_ERROR",
                "message": "An unexpected error occurred. Please try again later.",
            },
        )


# ── Root health endpoint ──────────────────────────────────────────────────────

app = create_app()


@app.get("/", tags=["Root"], summary="Root health check")
async def root() -> dict:
    return {
        "service": settings.APP_NAME,
        "version": settings.APP_VERSION,
        "status": "running",
        "environment": settings.APP_ENV,
    }